version: '3.8'

services:
  southwest-checkin:
    image: jdholtz/auto-southwest-check-in
    container_name: southwest-checkin
    restart: unless-stopped
    environment:
      - AUTO_SOUTHWEST_CHECK_IN_USERNAME=grobartlou
      - AUTO_SOUTHWEST_CHECK_IN_PASSWORD=Lou8103617

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - ${HOME}/jellyfin-config:/config
      - ${HOME}/jellyfin-cache:/cache
      - /mnt/hdd1:/hdd1:ro
      - /mnt/hdd2:/hdd2:ro
      - /mnt/hdd3:/hdd3:ro
      - /mnt/hdd4:/hdd4:ro
    devices:
      - /dev/dri:/dev/dri

  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: unless-stopped
    ports:
      - 4533:4533
    environment:
      - ND_LOGLEVEL=info
    volumes:
      - ${HOME}/navidrome-data:/data
      - /mnt/hdd1/Music:/music1:ro
      - /mnt/hdd2/Music:/music2:ro
      - /mnt/hdd3/Music:/music3:ro

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  portainer-data:
